version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    reviewers:
      - ewagriusz
    assignees:
      - ewagriusz
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
